# Generated by Django 6.0.7 on 2026-08-20 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_lead", "New Lead"),
                            ("lead_assigned", "Lead Assigned"),
                            ("deal_created", "Deal Created"),
                            ("deal_won", "Deal Won"),
                            ("deal_lost", "Deal Lost"),
                            ("task_due", "Task Due"),
                            ("task_assigned", "Task Assigned"),
                            ("followup_due", "Follow-up Due"),
                            ("customer_added", "Customer Added"),
                            ("login_alert", "Login Alert"),
                            ("backup_done", "Backup Completed"),
                            ("system_error", "System Error"),
                            ("weekly_report", "Weekly Report"),
                            ("monthly_report", "Monthly Report"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"], name="notif_user_read_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"], name="notif_user_created_idx"
                    ),
                ],
            },
        ),
    ]
