# Generated by Django 6.0.7 on 2026-08-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_lead", "New Lead"),
                    ("lead_assigned", "Lead Assigned"),
                    ("deal_created", "Deal Created"),
                    ("deal_won", "Deal Won"),
                    ("deal_lost", "Deal Lost"),
                    ("task_due", "Task Due"),
                    ("task_assigned", "Task Assigned"),
                    ("followup_due", "Follow-up Due"),
                    ("customer_added", "Customer Added"),
                    ("opportunity_created", "Opportunity Created"),
                    ("activity", "Activity"),
                    ("login_alert", "Login Alert"),
                    ("backup_done", "Backup Completed"),
                    ("system_error", "System Error"),
                    ("weekly_report", "Weekly Report"),
                    ("monthly_report", "Monthly Report"),
                ],
                max_length=30,
            ),
        ),
    ]
