# Generated by Django 6.0.7 on 2026-08-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="closed_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
