# Generated by Django 6.0.7 on 2026-08-15 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_templates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emailtemplate",
            name="email_templ_categor_63d385_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailtemplate",
            name="email_templ_status_00b662_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailtemplate",
            name="email_templ_templat_c39c9b_idx",
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["is_deleted", "category"], name="email_tpl_deleted_category_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["is_deleted", "status"], name="email_tpl_deleted_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["is_deleted", "template_type"],
                name="email_tpl_deleted_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["is_deleted", "-updated_at"],
                name="email_tpl_deleted_updated_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="templateactivity",
            index=models.Index(
                fields=["template", "-timestamp"],
                name="template_activity_template_time_idx",
            ),
        ),
    ]
