# Generated by Django 6.0.7 on 2026-08-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "email_templates",
            "0002_remove_emailtemplate_email_templ_categor_63d385_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emailtemplate",
            new_name="tpl_activity_time_idx",
            old_name="email_tpl_deleted_category_idx",
        ),
    ]
