# Generated by Django 6.0.7 on 2026-08-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "email_templates",
            "0003_rename_email_tpl_deleted_category_idx_tpl_activity_time_idx",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emailtemplate",
            new_name="etpl_delete_cat_idx",
            old_name="tpl_activity_time_idx",
        ),
        migrations.RenameIndex(
            model_name="emailtemplate",
            new_name="etpl_delete_sts_idx",
            old_name="email_tpl_deleted_status_idx",
        ),
        migrations.RenameIndex(
            model_name="emailtemplate",
            new_name="etpl_delete_type_idx",
            old_name="email_tpl_deleted_type_idx",
        ),
        migrations.RenameIndex(
            model_name="emailtemplate",
            new_name="etpl_delete_upd_idx",
            old_name="email_tpl_deleted_updated_idx",
        ),
        migrations.RenameIndex(
            model_name="templateactivity",
            new_name="tpl_activity_time_idx",
            old_name="template_activity_template_time_idx",
        ),
    ]
