# Generated by Django 6.0.7 on 2026-08-24 18:48

import project_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, default='', max_length=150)),
                ('project_code', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('project_description', models.TextField(blank=True, default='', max_length=1000)),
                ('project_timezone', models.CharField(blank=True, default='UTC', max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to=project_settings.models.project_logo_upload_to)),
                ('logo_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.URLField(blank=True, default='')),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('industry', models.CharField(blank=True, default='', max_length=150)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('tax_number', models.CharField(blank=True, default='', max_length=50)),
                ('currency', models.CharField(blank=True, choices=[('PKR - Pakistani Rupee (Rs.)', 'PKR - Pakistani Rupee (Rs.)'), ('USD - US Dollar ($)', 'USD - US Dollar ($)'), ('EUR - Euro (€)', 'EUR - Euro (€)'), ('GBP - British Pound (£)', 'GBP - British Pound (£)'), ('AED - UAE Dirham (د.إ)', 'AED - UAE Dirham (د.إ)')], default='PKR - Pakistani Rupee (Rs.)', max_length=50)),
                ('company_description', models.TextField(blank=True, default='', max_length=500)),
                ('language', models.CharField(blank=True, default='English (en)', max_length=50)),
                ('region', models.CharField(blank=True, default='Pakistan', max_length=100)),
                ('timezone', models.CharField(blank=True, default='(GMT+05:00) Asia/Karachi', max_length=100)),
                ('week_starts_on', models.CharField(choices=[('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Saturday', 'Saturday')], default='Monday', max_length=10)),
                ('fiscal_year_start', models.CharField(blank=True, default='January', max_length=20)),
                ('date_format', models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20)),
                ('time_format', models.CharField(choices=[('12 Hour (AM/PM)', '12 Hour (AM/PM)'), ('24 Hour', '24 Hour')], default='12 Hour (AM/PM)', max_length=20)),
                ('datetime_format', models.CharField(blank=True, default='DD/MM/YYYY hh:mm A', max_length=40)),
                ('localization_currency', models.CharField(blank=True, choices=[('PKR - Pakistani Rupee (Rs.)', 'PKR - Pakistani Rupee (Rs.)'), ('USD - US Dollar ($)', 'USD - US Dollar ($)'), ('EUR - Euro (€)', 'EUR - Euro (€)'), ('GBP - British Pound (£)', 'GBP - British Pound (£)'), ('AED - UAE Dirham (د.إ)', 'AED - UAE Dirham (د.إ)')], default='PKR - Pakistani Rupee (Rs.)', max_length=50)),
                ('currency_position', models.CharField(blank=True, default='Before Amount (Rs. 1,234.56)', max_length=50)),
                ('decimal_separator', models.CharField(blank=True, default='.', max_length=1)),
                ('thousands_separator', models.CharField(blank=True, default=',', max_length=1)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('from_name', models.CharField(blank=True, default='', max_length=150)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('email_signature', models.TextField(blank=True, default='', max_length=2000)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_encryption', models.CharField(choices=[('STARTTLS', 'STARTTLS'), ('SSL/TLS', 'SSL/TLS'), ('None', 'None')], default='STARTTLS', max_length=20)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('enable_email_tracking', models.BooleanField(default=True)),
                ('enable_link_tracking', models.BooleanField(default=True)),
                ('log_emails_to_activity', models.BooleanField(default=False)),
                ('attach_email_signature', models.BooleanField(default=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('login_notifications', models.BooleanField(default=True)),
                ('session_timeout', models.PositiveIntegerField(default=30)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('password_expiry_days', models.PositiveIntegerField(default=90)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('require_numbers', models.BooleanField(default=True)),
                ('require_special_chars', models.BooleanField(default=False)),
                ('min_password_length', models.PositiveSmallIntegerField(default=8)),
                ('ip_whitelist', models.TextField(blank=True, default='')),
                ('force_https', models.BooleanField(default=True)),
                ('audit_log', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Settings',
                'verbose_name_plural': 'Project Settings',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('access_level', models.CharField(choices=[('full', 'Full system access'), ('team', 'Manage team and data'), ('sales', 'Manage leads, opportunities, and deals'), ('view', 'View-only access'), ('custom', 'Custom access')], default='custom', max_length=20)),
                ('color', models.CharField(blank=True, default='#4f46e5', max_length=20)),
                ('bg_color', models.CharField(blank=True, default='#eef2ff', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('users_assigned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
