# Generated by Django 6.0.7 on 2026-08-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={},
        ),
        migrations.RemoveField(
            model_name="note",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="note",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="note",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="note",
            name="deal",
        ),
        migrations.RemoveField(
            model_name="note",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="note",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="note",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=20,
            ),
        ),
    ]
